export const SET_USER_SEARCH = "SET_USER_SEARCH";

export const SET_CURRENT_HIKE = "SET_CURRENT_HIKE";

export const UPDATE_HIKES = "UPDATE_HIKES";

export const UPDATE_LAT_LON = "UPDATE_LAT_LON"

export const ADD_BUCKETLIST = "ADD_BUCKETLIST";
export const REMOVE_BUCKETLIST = "REMOVE_BUCKETLIST";
export const UPDATE_BUCKETLIST = "UPDATE_BUCKETLIST";

export const ADD_LOG = "ADD_LOG";
export const REMOVE_LOG = "ROMOVE_LOG";
export const UPDATE_LOG= "UPDATE_LOG";

export const LOADING = "LOADING";

export const UPDATE_LINE_CHART = "UPDATE_LINE_CHART";
export const UPDATE_BAR_CHART = "UPDATE_BAR_CHART";
export const UPDATE_LINE_CHART_LABELS = "UPDATE_LINE_CHART_LABELS";
export const UPDATE_BAR_CHART_LABELS = "UPDATE_BAR_CHART_LABELS";
export const UPDATE_BAR_LABEL_STYLE = "UPDATE_BAR_LABEL_STYLE";
export const UPDATE_LINE_LABEL_STYLE = "UPDATE_LINE_LABEL_STYLE";

export const SET_GOOGLE_ID = "SET_GOOGLE_ID";
export const SET_NAME = "SET_NAME";

export const SET_ACTION_NOTIFICATION = "SET_ACTION_NOTIFICATION"
export const CATCH_FORECAST = "CATCH_FORECASE";
export const SET_FORECAST_LOCATION = "SET_FORECAST_LOCATION";
